### ISSUE TITLE
Aufgabenstellung

### ISSUE THREAD

**Issue by KatharinaNiederpruem** [drheisel/MALIS-21.3-WPM_T9_Carina_Heisel#2]
Ich würde die Aufgabenstellung mittelfristig kürzen und eher ins README verschieben. Das macht die Sache m.M.n. übersichtlicher.

**Comment by drheisel** [comment]
Das ist richtig und ist auch mein Plan. :thumbsup:

Aktuell mag ich es ganz gerne, wenn ich da schnell mal runter scrollen kann. Außerdem habe ich damit mein Markdown wieder ein wenig aufgefrischt. :smile:
